create table if not exists projects(
    id  integer primary key generated  by DEFAULT as IDENTITY,
    name  text not null  check (name <> ""),
    priority integer not null,
    description text,
    deliverydate date not null
);

create table if not exists tasks(
id integer primary key generated by DEFAULT as IDENTITY,
name text not null check (name <> ""),
done boolean,
projectId integer references projects(id)
);